library(RCurl)
library(rjson)
library(anytime)
library(tidyverse)
library(lubridate)
json <- ('https://poloniex.com/public?command=returnChartData&currencyPair=USDT_BTC&start=1435699200&end=9999999999&period=14400'); BTC <- fromJSON(file = json); BTC <- do.call(rbind.data.frame, BTC); BTC$date<-anytime(BTC$date); BTC$hour3 <- lubridate::floor_date(BTC$date , '3 hours')
json <- ('https://poloniex.com/public?command=returnChartData&currencyPair=BTC_LTC&start=1435699200&end=9999999999&period=14400'); LTC <- fromJSON(file = json); LTC <- do.call(rbind.data.frame, LTC); LTC$date<-anytime(LTC$date); LTC$hour3 <- lubridate::floor_date(LTC$date , '3 hours')
json <- ('https://poloniex.com/public?command=returnChartData&currencyPair=BTC_ETH&start=1435699200&end=9999999999&period=14400'); ETH <- fromJSON(file = json); ETH <- do.call(rbind.data.frame, ETH); ETH$date<-anytime(ETH$date); ETH$hour3 <- lubridate::floor_date(ETH$date , '3 hours')
json <- ('https://poloniex.com/public?command=returnChartData&currencyPair=BTC_XRP&start=1435699200&end=9999999999&period=14400'); XRP <- fromJSON(file = json); XRP <- do.call(rbind.data.frame, XRP); XRP$date<-anytime(XRP$date); XRP$hour3 <- lubridate::floor_date(XRP$date , '3 hours')
json <- ('https://poloniex.com/public?command=returnChartData&currencyPair=BTC_BCH&start=1435699200&end=9999999999&period=14400'); BCH <- fromJSON(file = json); BCH <- do.call(rbind.data.frame, BCH); BCH$date<-anytime(BCH$date); BCH$hour3 <- lubridate::floor_date(BCH$date , '3 hours')
json <- ('https://poloniex.com/public?command=returnChartData&currencyPair=BTC_STR&start=1435699200&end=9999999999&period=14400'); STR <- fromJSON(file = json); STR <- do.call(rbind.data.frame, STR); STR$date<-anytime(STR$date); STR$hour3 <- lubridate::floor_date(STR$date , '3 hours')
json <- ('https://poloniex.com/public?command=returnChartData&currencyPair=BTC_XMR&start=1435699200&end=9999999999&period=14400'); XMR <- fromJSON(file = json); XMR <- do.call(rbind.data.frame, XMR); XMR$date<-anytime(XMR$date); XMR$hour3 <- lubridate::floor_date(XMR$date , '3 hours')
json <- ('https://poloniex.com/public?command=returnChartData&currencyPair=BTC_XEM&start=1435699200&end=9999999999&period=14400'); XEM <- fromJSON(file = json); XEM <- do.call(rbind.data.frame, XEM); XEM$date<-anytime(XEM$date); XEM$hour3 <- lubridate::floor_date(XEM$date , '3 hours')
json <- ('https://poloniex.com/public?command=returnChartData&currencyPair=BTC_ETC&start=1435699200&end=9999999999&period=14400'); ETC <- fromJSON(file = json); ETC <- do.call(rbind.data.frame, ETC); ETC$date<-anytime(ETC$date); ETC$hour3 <- lubridate::floor_date(ETC$date , '3 hours')
json <- ('https://poloniex.com/public?command=returnChartData&currencyPair=BTC_DASH&start=1435699200&end=9999999999&period=14400'); DASH <- fromJSON(file = json); DASH <- do.call(rbind.data.frame, DASH); DASH$date<-anytime(DASH$date); DASH$hour3 <- lubridate::floor_date(DASH$date , '3 hours')
json <- ('https://poloniex.com/public?command=returnChartData&currencyPair=BTC_STRAT&start=1435699200&end=9999999999&period=14400'); STRAT <- fromJSON(file = json); STRAT <- do.call(rbind.data.frame, STRAT); STRAT$date<-anytime(STRAT$date); STRAT$hour3 <- lubridate::floor_date(STRAT$date , '3 hours')
json <- ('https://poloniex.com/public?command=returnChartData&currencyPair=BTC_NXT&start=1435699200&end=9999999999&period=14400'); NXT <- fromJSON(file = json); NXT <- do.call(rbind.data.frame, NXT); NXT$date<-anytime(NXT$date); NXT$hour3 <- lubridate::floor_date(NXT$date , '3 hours')
json <- ('https://poloniex.com/public?command=returnChartData&currencyPair=BTC_ZEC&start=1435699200&end=9999999999&period=14400'); ZEC <- fromJSON(file = json); ZEC <- do.call(rbind.data.frame, ZEC); ZEC$date<-anytime(ZEC$date); ZEC$hour3 <- lubridate::floor_date(ZEC$date , '3 hours')
json <- ('https://poloniex.com/public?command=returnChartData&currencyPair=BTC_EMC2&start=1435699200&end=9999999999&period=14400'); EMC2 <- fromJSON(file = json); EMC2 <- do.call(rbind.data.frame, EMC2); EMC2$date<-anytime(EMC2$date); EMC2$hour3 <- lubridate::floor_date(EMC2$date , '3 hours')
json <- ('https://poloniex.com/public?command=returnChartData&currencyPair=BTC_ARDR&start=1435699200&end=9999999999&period=14400'); ARDR <- fromJSON(file = json); ARDR <- do.call(rbind.data.frame, ARDR); ARDR$date<-anytime(ARDR$date); ARDR$hour3 <- lubridate::floor_date(ARDR$date , '3 hours')
json <- ('https://poloniex.com/public?command=returnChartData&currencyPair=BTC_LSK&start=1435699200&end=9999999999&period=14400'); LSK <- fromJSON(file = json); LSK <- do.call(rbind.data.frame, LSK); LSK$date<-anytime(LSK$date); LSK$hour3 <- lubridate::floor_date(LSK$date , '3 hours')
json <- ('https://poloniex.com/public?command=returnChartData&currencyPair=BTC_DOGE&start=1435699200&end=9999999999&period=14400'); DOGE <- fromJSON(file = json); DOGE <- do.call(rbind.data.frame, DOGE); DOGE$date<-anytime(DOGE$date); DOGE$hour3 <- lubridate::floor_date(DOGE$date , '3 hours')
json <- ('https://poloniex.com/public?command=returnChartData&currencyPair=BTC_VTC&start=1435699200&end=9999999999&period=14400'); VTC <- fromJSON(file = json); VTC <- do.call(rbind.data.frame, VTC); VTC$date<-anytime(VTC$date); VTC$hour3 <- lubridate::floor_date(VTC$date , '3 hours')
json <- ('https://poloniex.com/public?command=returnChartData&currencyPair=BTC_BTS&start=1435699200&end=9999999999&period=14400'); BTS <- fromJSON(file = json); BTS <- do.call(rbind.data.frame, BTS); BTS$date<-anytime(BTS$date); BTS$hour3 <- lubridate::floor_date(BTS$date , '3 hours')
json <- ('https://poloniex.com/public?command=returnChartData&currencyPair=BTC_OMG&start=1435699200&end=9999999999&period=14400'); OMG <- fromJSON(file = json); OMG <- do.call(rbind.data.frame, OMG); OMG$date<-anytime(OMG$date); OMG$hour3 <- lubridate::floor_date(OMG$date , '3 hours')
json <- ('https://poloniex.com/public?command=returnChartData&currencyPair=BTC_SC&start=1435699200&end=9999999999&period=14400'); SC <- fromJSON(file = json); SC <- do.call(rbind.data.frame, SC); SC$date<-anytime(SC$date); SC$hour3 <- lubridate::floor_date(SC$date , '3 hours')
json <- ('https://poloniex.com/public?command=returnChartData&currencyPair=BTC_DGB&start=1435699200&end=9999999999&period=14400'); DGB <- fromJSON(file = json); DGB <- do.call(rbind.data.frame, DGB); DGB$date<-anytime(DGB$date); DGB$hour3 <- lubridate::floor_date(DGB$date , '3 hours')
json <- ('https://poloniex.com/public?command=returnChartData&currencyPair=BTC_FCT&start=1435699200&end=9999999999&period=14400'); FCT <- fromJSON(file = json); FCT <- do.call(rbind.data.frame, FCT); FCT$date<-anytime(FCT$date); FCT$hour3 <- lubridate::floor_date(FCT$date , '3 hours')
json <- ('https://poloniex.com/public?command=returnChartData&currencyPair=BTC_MAID&start=1435699200&end=9999999999&period=14400'); MAID <- fromJSON(file = json); MAID <- do.call(rbind.data.frame, MAID); MAID$date<-anytime(MAID$date); MAID$hour3 <- lubridate::floor_date(MAID$date , '3 hours')
json <- ('https://poloniex.com/public?command=returnChartData&currencyPair=BTC_FLDC&start=1435699200&end=9999999999&period=14400'); FLDC <- fromJSON(file = json); FLDC <- do.call(rbind.data.frame, FLDC); FLDC$date<-anytime(FLDC$date); FLDC$hour3 <- lubridate::floor_date(FLDC$date , '3 hours')
json <- ('https://poloniex.com/public?command=returnChartData&currencyPair=BTC_VRC&start=1435699200&end=9999999999&period=14400'); VRC <- fromJSON(file = json); VRC <- do.call(rbind.data.frame, VRC); VRC$date<-anytime(VRC$date); VRC$hour3 <- lubridate::floor_date(VRC$date , '3 hours')
json <- ('https://poloniex.com/public?command=returnChartData&currencyPair=BTC_REP&start=1435699200&end=9999999999&period=14400'); REP <- fromJSON(file = json); REP <- do.call(rbind.data.frame, REP); REP$date<-anytime(REP$date); REP$hour3 <- lubridate::floor_date(REP$date , '3 hours')
json <- ('https://poloniex.com/public?command=returnChartData&currencyPair=BTC_ZRX&start=1435699200&end=9999999999&period=14400'); ZRX <- fromJSON(file = json); ZRX <- do.call(rbind.data.frame, ZRX); ZRX$date<-anytime(ZRX$date); ZRX$hour3 <- lubridate::floor_date(ZRX$date , '3 hours')
json <- ('https://poloniex.com/public?command=returnChartData&currencyPair=BTC_GNO&start=1435699200&end=9999999999&period=14400'); GNO <- fromJSON(file = json); GNO <- do.call(rbind.data.frame, GNO); GNO$date<-anytime(GNO$date); GNO$hour3 <- lubridate::floor_date(GNO$date , '3 hours')
json <- ('https://poloniex.com/public?command=returnChartData&currencyPair=BTC_CVC&start=1435699200&end=9999999999&period=14400'); CVC <- fromJSON(file = json); CVC <- do.call(rbind.data.frame, CVC); CVC$date<-anytime(CVC$date); CVC$hour3 <- lubridate::floor_date(CVC$date , '3 hours')
json <- ('https://poloniex.com/public?command=returnChartData&currencyPair=BTC_DCR&start=1435699200&end=9999999999&period=14400'); DCR <- fromJSON(file = json); DCR <- do.call(rbind.data.frame, DCR); DCR$date<-anytime(DCR$date); DCR$hour3 <- lubridate::floor_date(DCR$date , '3 hours')
json <- ('https://poloniex.com/public?command=returnChartData&currencyPair=BTC_GNT&start=1435699200&end=9999999999&period=14400'); GNT <- fromJSON(file = json); GNT <- do.call(rbind.data.frame, GNT); GNT$date<-anytime(GNT$date); GNT$hour3 <- lubridate::floor_date(GNT$date , '3 hours')
json <- ('https://poloniex.com/public?command=returnChartData&currencyPair=BTC_SYS&start=1435699200&end=9999999999&period=14400'); SYS <- fromJSON(file = json); SYS <- do.call(rbind.data.frame, SYS); SYS$date<-anytime(SYS$date); SYS$hour3 <- lubridate::floor_date(SYS$date , '3 hours')
json <- ('https://poloniex.com/public?command=returnChartData&currencyPair=BTC_STEEM&start=1435699200&end=9999999999&period=14400'); STEEM <- fromJSON(file = json); STEEM <- do.call(rbind.data.frame, STEEM); STEEM$date<-anytime(STEEM$date); STEEM$hour3 <- lubridate::floor_date(STEEM$date , '3 hours')
json <- ('https://poloniex.com/public?command=returnChartData&currencyPair=BTC_GAME&start=1435699200&end=9999999999&period=14400'); GAME <- fromJSON(file = json); GAME <- do.call(rbind.data.frame, GAME); GAME$date<-anytime(GAME$date); GAME$hour3 <- lubridate::floor_date(GAME$date , '3 hours')
json <- ('https://poloniex.com/public?command=returnChartData&currencyPair=BTC_LBC&start=1435699200&end=9999999999&period=14400'); LBC <- fromJSON(file = json); LBC <- do.call(rbind.data.frame, LBC); LBC$date<-anytime(LBC$date); LBC$hour3 <- lubridate::floor_date(LBC$date , '3 hours')
json <- ('https://poloniex.com/public?command=returnChartData&currencyPair=BTC_NAV&start=1435699200&end=9999999999&period=14400'); NAV <- fromJSON(file = json); NAV <- do.call(rbind.data.frame, NAV); NAV$date<-anytime(NAV$date); NAV$hour3 <- lubridate::floor_date(NAV$date , '3 hours')
json <- ('https://poloniex.com/public?command=returnChartData&currencyPair=BTC_BCN&start=1435699200&end=9999999999&period=14400'); BCN <- fromJSON(file = json); BCN <- do.call(rbind.data.frame, BCN); BCN$date<-anytime(BCN$date); BCN$hour3 <- lubridate::floor_date(BCN$date , '3 hours')
json <- ('https://poloniex.com/public?command=returnChartData&currencyPair=BTC_AMP&start=1435699200&end=9999999999&period=14400'); AMP <- fromJSON(file = json); AMP <- do.call(rbind.data.frame, AMP); AMP$date<-anytime(AMP$date); AMP$hour3 <- lubridate::floor_date(AMP$date , '3 hours')
json <- ('https://poloniex.com/public?command=returnChartData&currencyPair=BTC_CLAM&start=1435699200&end=9999999999&period=14400'); CLAM <- fromJSON(file = json); CLAM <- do.call(rbind.data.frame, CLAM); CLAM$date<-anytime(CLAM$date); CLAM$hour3 <- lubridate::floor_date(CLAM$date , '3 hours')
json <- ('https://poloniex.com/public?command=returnChartData&currencyPair=BTC_POT&start=1435699200&end=9999999999&period=14400'); POT <- fromJSON(file = json); POT <- do.call(rbind.data.frame, POT); POT$date<-anytime(POT$date); POT$hour3 <- lubridate::floor_date(POT$date , '3 hours')
json <- ('https://poloniex.com/public?command=returnChartData&currencyPair=BTC_STORJ&start=1435699200&end=9999999999&period=14400'); STORJ <- fromJSON(file = json); STORJ <- do.call(rbind.data.frame, STORJ); STORJ$date<-anytime(STORJ$date); STORJ$hour3 <- lubridate::floor_date(STORJ$date , '3 hours')
json <- ('https://poloniex.com/public?command=returnChartData&currencyPair=BTC_RIC&start=1435699200&end=9999999999&period=14400'); RIC <- fromJSON(file = json); RIC <- do.call(rbind.data.frame, RIC); RIC$date<-anytime(RIC$date); RIC$hour3 <- lubridate::floor_date(RIC$date , '3 hours')
json <- ('https://poloniex.com/public?command=returnChartData&currencyPair=BTC_BURST&start=1435699200&end=9999999999&period=14400'); BURST <- fromJSON(file = json); BURST <- do.call(rbind.data.frame, BURST); BURST$date<-anytime(BURST$date); BURST$hour3 <- lubridate::floor_date(BURST$date , '3 hours')
json <- ('https://poloniex.com/public?command=returnChartData&currencyPair=BTC_PPC&start=1435699200&end=9999999999&period=14400'); PPC <- fromJSON(file = json); PPC <- do.call(rbind.data.frame, PPC); PPC$date<-anytime(PPC$date); PPC$hour3 <- lubridate::floor_date(PPC$date , '3 hours')
json <- ('https://poloniex.com/public?command=returnChartData&currencyPair=BTC_BLK&start=1435699200&end=9999999999&period=14400'); BLK <- fromJSON(file = json); BLK <- do.call(rbind.data.frame, BLK); BLK$date<-anytime(BLK$date); BLK$hour3 <- lubridate::floor_date(BLK$date , '3 hours')
json <- ('https://poloniex.com/public?command=returnChartData&currencyPair=BTC_PASC&start=1435699200&end=9999999999&period=14400'); PASC <- fromJSON(file = json); PASC <- do.call(rbind.data.frame, PASC); PASC$date<-anytime(PASC$date); PASC$hour3 <- lubridate::floor_date(PASC$date , '3 hours')
json <- ('https://poloniex.com/public?command=returnChartData&currencyPair=BTC_GAS&start=1435699200&end=9999999999&period=14400'); GAS <- fromJSON(file = json); GAS <- do.call(rbind.data.frame, GAS); GAS$date<-anytime(GAS$date); GAS$hour3 <- lubridate::floor_date(GAS$date , '3 hours')
json <- ('https://poloniex.com/public?command=returnChartData&currencyPair=BTC_GRC&start=1435699200&end=9999999999&period=14400'); GRC <- fromJSON(file = json); GRC <- do.call(rbind.data.frame, GRC); GRC$date<-anytime(GRC$date); GRC$hour3 <- lubridate::floor_date(GRC$date , '3 hours')
json <- ('https://poloniex.com/public?command=returnChartData&currencyPair=BTC_SBD&start=1435699200&end=9999999999&period=14400'); SBD <- fromJSON(file = json); SBD <- do.call(rbind.data.frame, SBD); SBD$date<-anytime(SBD$date); SBD$hour3 <- lubridate::floor_date(SBD$date , '3 hours')
json <- ('https://poloniex.com/public?command=returnChartData&currencyPair=BTC_XCP&start=1435699200&end=9999999999&period=14400'); XCP <- fromJSON(file = json); XCP <- do.call(rbind.data.frame, XCP); XCP$date<-anytime(XCP$date); XCP$hour3 <- lubridate::floor_date(XCP$date , '3 hours')
json <- ('https://poloniex.com/public?command=returnChartData&currencyPair=BTC_BTM&start=1435699200&end=9999999999&period=14400'); BTM <- fromJSON(file = json); BTM <- do.call(rbind.data.frame, BTM); BTM$date<-anytime(BTM$date); BTM$hour3 <- lubridate::floor_date(BTM$date , '3 hours')
json <- ('https://poloniex.com/public?command=returnChartData&currencyPair=BTC_EXP&start=1435699200&end=9999999999&period=14400'); EXP <- fromJSON(file = json); EXP <- do.call(rbind.data.frame, EXP); EXP$date<-anytime(EXP$date); EXP$hour3 <- lubridate::floor_date(EXP$date , '3 hours')
json <- ('https://poloniex.com/public?command=returnChartData&currencyPair=BTC_VIA&start=1435699200&end=9999999999&period=14400'); VIA <- fromJSON(file = json); VIA <- do.call(rbind.data.frame, VIA); VIA$date<-anytime(VIA$date); VIA$hour3 <- lubridate::floor_date(VIA$date , '3 hours')
json <- ('https://poloniex.com/public?command=returnChartData&currencyPair=BTC_BTCD&start=1435699200&end=9999999999&period=14400'); BTCD <- fromJSON(file = json); BTCD <- do.call(rbind.data.frame, BTCD); BTCD$date<-anytime(BTCD$date); BTCD$hour3 <- lubridate::floor_date(BTCD$date , '3 hours')
json <- ('https://poloniex.com/public?command=returnChartData&currencyPair=BTC_RADS&start=1435699200&end=9999999999&period=14400'); RADS <- fromJSON(file = json); RADS <- do.call(rbind.data.frame, RADS); RADS$date<-anytime(RADS$date); RADS$hour3 <- lubridate::floor_date(RADS$date , '3 hours')
json <- ('https://poloniex.com/public?command=returnChartData&currencyPair=BTC_FLO&start=1435699200&end=9999999999&period=14400'); FLO <- fromJSON(file = json); FLO <- do.call(rbind.data.frame, FLO); FLO$date<-anytime(FLO$date); FLO$hour3 <- lubridate::floor_date(FLO$date , '3 hours')
json <- ('https://poloniex.com/public?command=returnChartData&currencyPair=BTC_NEOS&start=1435699200&end=9999999999&period=14400'); NEOS <- fromJSON(file = json); NEOS <- do.call(rbind.data.frame, NEOS); NEOS$date<-anytime(NEOS$date); NEOS$hour3 <- lubridate::floor_date(NEOS$date , '3 hours')
json <- ('https://poloniex.com/public?command=returnChartData&currencyPair=BTC_NMC&start=1435699200&end=9999999999&period=14400'); NMC <- fromJSON(file = json); NMC <- do.call(rbind.data.frame, NMC); NMC$date<-anytime(NMC$date); NMC$hour3 <- lubridate::floor_date(NMC$date , '3 hours')
json <- ('https://poloniex.com/public?command=returnChartData&currencyPair=BTC_NXC&start=1435699200&end=9999999999&period=14400'); NXC <- fromJSON(file = json); NXC <- do.call(rbind.data.frame, NXC); NXC$date<-anytime(NXC$date); NXC$hour3 <- lubridate::floor_date(NXC$date , '3 hours')
json <- ('https://poloniex.com/public?command=returnChartData&currencyPair=BTC_XBC&start=1435699200&end=9999999999&period=14400'); XBC <- fromJSON(file = json); XBC <- do.call(rbind.data.frame, XBC); XBC$date<-anytime(XBC$date); XBC$hour3 <- lubridate::floor_date(XBC$date , '3 hours')
json <- ('https://poloniex.com/public?command=returnChartData&currencyPair=BTC_XVC&start=1435699200&end=9999999999&period=14400'); XVC <- fromJSON(file = json); XVC <- do.call(rbind.data.frame, XVC); XVC$date<-anytime(XVC$date); XVC$hour3 <- lubridate::floor_date(XVC$date , '3 hours')
json <- ('https://poloniex.com/public?command=returnChartData&currencyPair=BTC_PINK&start=1435699200&end=9999999999&period=14400'); PINK <- fromJSON(file = json); PINK <- do.call(rbind.data.frame, PINK); PINK$date<-anytime(PINK$date); PINK$hour3 <- lubridate::floor_date(PINK$date , '3 hours')
json <- ('https://poloniex.com/public?command=returnChartData&currencyPair=BTC_OMNI&start=1435699200&end=9999999999&period=14400'); OMNI <- fromJSON(file = json); OMNI <- do.call(rbind.data.frame, OMNI); OMNI$date<-anytime(OMNI$date); OMNI$hour3 <- lubridate::floor_date(OMNI$date , '3 hours')
json <- ('https://poloniex.com/public?command=returnChartData&currencyPair=BTC_BELA&start=1435699200&end=9999999999&period=14400'); BELA <- fromJSON(file = json); BELA <- do.call(rbind.data.frame, BELA); BELA$date<-anytime(BELA$date); BELA$hour3 <- lubridate::floor_date(BELA$date , '3 hours')
json <- ('https://poloniex.com/public?command=returnChartData&currencyPair=BTC_BCY&start=1435699200&end=9999999999&period=14400'); BCY <- fromJSON(file = json); BCY <- do.call(rbind.data.frame, BCY); BCY$date<-anytime(BCY$date); BCY$hour3 <- lubridate::floor_date(BCY$date , '3 hours')
json <- ('https://poloniex.com/public?command=returnChartData&currencyPair=BTC_HUC&start=1435699200&end=9999999999&period=14400'); HUC <- fromJSON(file = json); HUC <- do.call(rbind.data.frame, HUC); HUC$date<-anytime(HUC$date); HUC$hour3 <- lubridate::floor_date(HUC$date , '3 hours')
json <- ('https://poloniex.com/public?command=returnChartData&currencyPair=BTC_XPM&start=1435699200&end=9999999999&period=14400'); XPM <- fromJSON(file = json); XPM <- do.call(rbind.data.frame, XPM); XPM$date<-anytime(XPM$date); XPM$hour3 <- lubridate::floor_date(XPM$date , '3 hours')


BTC.close<-BTC %>% group_by(hour3) %>%  summarise(close.BTC=mean(close))
LTC.close<-LTC %>% group_by(hour3) %>%  summarise(close.LTC=mean(close))
ETH.close<-ETH %>% group_by(hour3) %>%  summarise(close.ETH=mean(close))
XRP.close<-XRP %>% group_by(hour3) %>%  summarise(close.XRP=mean(close))
BCH.close<-BCH %>% group_by(hour3) %>%  summarise(close.BCH=mean(close))
STR.close<-STR %>% group_by(hour3) %>%  summarise(close.STR=mean(close))
XMR.close<-XMR %>% group_by(hour3) %>%  summarise(close.XMR=mean(close))
XEM.close<-XEM %>% group_by(hour3) %>%  summarise(close.XEM=mean(close))
ETC.close<-ETC %>% group_by(hour3) %>%  summarise(close.ETC=mean(close))
DASH.close<-DASH %>% group_by(hour3) %>%  summarise(close.DASH=mean(close))
STRAT.close<-STRAT %>% group_by(hour3) %>%  summarise(close.STRAT=mean(close))
NXT.close<-NXT %>% group_by(hour3) %>%  summarise(close.NXT=mean(close))
ZEC.close<-ZEC %>% group_by(hour3) %>%  summarise(close.ZEC=mean(close))
EMC2.close<-EMC2 %>% group_by(hour3) %>%  summarise(close.EMC2=mean(close))
ARDR.close<-ARDR %>% group_by(hour3) %>%  summarise(close.ARDR=mean(close))
LSK.close<-LSK %>% group_by(hour3) %>%  summarise(close.LSK=mean(close))
DOGE.close<-DOGE %>% group_by(hour3) %>%  summarise(close.DOGE=mean(close))
VTC.close<-VTC %>% group_by(hour3) %>%  summarise(close.VTC=mean(close))
BTS.close<-BTS %>% group_by(hour3) %>%  summarise(close.BTS=mean(close))
OMG.close<-OMG %>% group_by(hour3) %>%  summarise(close.OMG=mean(close))
SC.close<-SC %>% group_by(hour3) %>%  summarise(close.SC=mean(close))
DGB.close<-DGB %>% group_by(hour3) %>%  summarise(close.DGB=mean(close))
FCT.close<-FCT %>% group_by(hour3) %>%  summarise(close.FCT=mean(close))
MAID.close<-MAID %>% group_by(hour3) %>%  summarise(close.MAID=mean(close))
FLDC.close<-FLDC %>% group_by(hour3) %>%  summarise(close.FLDC=mean(close))
VRC.close<-VRC %>% group_by(hour3) %>%  summarise(close.VRC=mean(close))
REP.close<-REP %>% group_by(hour3) %>%  summarise(close.REP=mean(close))
ZRX.close<-ZRX %>% group_by(hour3) %>%  summarise(close.ZRX=mean(close))
GNO.close<-GNO %>% group_by(hour3) %>%  summarise(close.GNO=mean(close))
CVC.close<-CVC %>% group_by(hour3) %>%  summarise(close.CVC=mean(close))
DCR.close<-DCR %>% group_by(hour3) %>%  summarise(close.DCR=mean(close))
GNT.close<-GNT %>% group_by(hour3) %>%  summarise(close.GNT=mean(close))
SYS.close<-SYS %>% group_by(hour3) %>%  summarise(close.SYS=mean(close))
STEEM.close<-STEEM %>% group_by(hour3) %>%  summarise(close.STEEM=mean(close))
GAME.close<-GAME %>% group_by(hour3) %>%  summarise(close.GAME=mean(close))
LBC.close<-LBC %>% group_by(hour3) %>%  summarise(close.LBC=mean(close))
NAV.close<-NAV %>% group_by(hour3) %>%  summarise(close.NAV=mean(close))
BCN.close<-BCN %>% group_by(hour3) %>%  summarise(close.BCN=mean(close))
AMP.close<-AMP %>% group_by(hour3) %>%  summarise(close.AMP=mean(close))
CLAM.close<-CLAM %>% group_by(hour3) %>%  summarise(close.CLAM=mean(close))
POT.close<-POT %>% group_by(hour3) %>%  summarise(close.POT=mean(close))
STORJ.close<-STORJ %>% group_by(hour3) %>%  summarise(close.STORJ=mean(close))
RIC.close<-RIC %>% group_by(hour3) %>%  summarise(close.RIC=mean(close))
BURST.close<-BURST %>% group_by(hour3) %>%  summarise(close.BURST=mean(close))
PPC.close<-PPC %>% group_by(hour3) %>%  summarise(close.PPC=mean(close))
BLK.close<-BLK %>% group_by(hour3) %>%  summarise(close.BLK=mean(close))
PASC.close<-PASC %>% group_by(hour3) %>%  summarise(close.PASC=mean(close))
GAS.close<-GAS %>% group_by(hour3) %>%  summarise(close.GAS=mean(close))
GRC.close<-GRC %>% group_by(hour3) %>%  summarise(close.GRC=mean(close))
SBD.close<-SBD %>% group_by(hour3) %>%  summarise(close.SBD=mean(close))
XCP.close<-XCP %>% group_by(hour3) %>%  summarise(close.XCP=mean(close))
BTM.close<-BTM %>% group_by(hour3) %>%  summarise(close.BTM=mean(close))
EXP.close<-EXP %>% group_by(hour3) %>%  summarise(close.EXP=mean(close))
VIA.close<-VIA %>% group_by(hour3) %>%  summarise(close.VIA=mean(close))
BTCD.close<-BTCD %>% group_by(hour3) %>%  summarise(close.BTCD=mean(close))
RADS.close<-RADS %>% group_by(hour3) %>%  summarise(close.RADS=mean(close))
FLO.close<-FLO %>% group_by(hour3) %>%  summarise(close.FLO=mean(close))
NEOS.close<-NEOS %>% group_by(hour3) %>%  summarise(close.NEOS=mean(close))
NMC.close<-NMC %>% group_by(hour3) %>%  summarise(close.NMC=mean(close))
NXC.close<-NXC %>% group_by(hour3) %>%  summarise(close.NXC=mean(close))
XBC.close<-XBC %>% group_by(hour3) %>%  summarise(close.XBC=mean(close))
XVC.close<-XVC %>% group_by(hour3) %>%  summarise(close.XVC=mean(close))
PINK.close<-PINK %>% group_by(hour3) %>%  summarise(close.PINK=mean(close))
OMNI.close<-OMNI %>% group_by(hour3) %>%  summarise(close.OMNI=mean(close))
BELA.close<-BELA %>% group_by(hour3) %>%  summarise(close.BELA=mean(close))
BCY.close<-BCY %>% group_by(hour3) %>%  summarise(close.BCY=mean(close))
HUC.close<-HUC %>% group_by(hour3) %>%  summarise(close.HUC=mean(close))
XPM.close<-XPM %>% group_by(hour3) %>%  summarise(close.XPM=mean(close))


full<- left_join(BTC.close,LTC.close, by='hour3') %>%     left_join(., ETH.close, by='hour3') 	%>%     left_join(., XRP.close, by='hour3') 	%>%     left_join(., BCH.close, by='hour3') 	%>%     left_join(., STR.close, by='hour3') 	%>%     left_join(., XMR.close, by='hour3') 	%>%     left_join(., XEM.close, by='hour3') 	%>%     left_join(., ETC.close, by='hour3') 	%>%     left_join(., DASH.close, by='hour3') 	%>%     left_join(., STRAT.close, by='hour3') 	%>%     left_join(., NXT.close, by='hour3') 	%>%     left_join(., ZEC.close, by='hour3') 	%>%     left_join(., EMC2.close, by='hour3') 	%>%     left_join(., ARDR.close, by='hour3') 	%>%     left_join(., LSK.close, by='hour3') 	%>%     left_join(., DOGE.close, by='hour3') 	%>%     left_join(., VTC.close, by='hour3') 	%>%     left_join(., BTS.close, by='hour3') 	%>%     left_join(., OMG.close, by='hour3') 	%>%     left_join(., SC.close, by='hour3') 	%>%     left_join(., DGB.close, by='hour3') 	%>%     left_join(., FCT.close, by='hour3') 	%>%     left_join(., MAID.close, by='hour3') 	%>%     left_join(., FLDC.close, by='hour3') 	%>%     left_join(., VRC.close, by='hour3') 	%>%     left_join(., REP.close, by='hour3') 	%>%     left_join(., ZRX.close, by='hour3') 	%>%     left_join(., GNO.close, by='hour3') 	%>%     left_join(., CVC.close, by='hour3') 	%>%     left_join(., DCR.close, by='hour3') 	%>%     left_join(., GNT.close, by='hour3') 	%>%     left_join(., SYS.close, by='hour3') 	%>%     left_join(., STEEM.close, by='hour3') 	%>%     left_join(., GAME.close, by='hour3') 	%>%     left_join(., LBC.close, by='hour3') 	%>%     left_join(., NAV.close, by='hour3') 	%>%     left_join(., BCN.close, by='hour3') 	%>%     left_join(., AMP.close, by='hour3') 	%>%     left_join(., CLAM.close, by='hour3') 	%>%     left_join(., POT.close, by='hour3') 	%>%     left_join(., STORJ.close, by='hour3') 	%>%     left_join(., RIC.close, by='hour3') 	%>%     left_join(., BURST.close, by='hour3') 	%>%     left_join(., PPC.close, by='hour3') 	%>%     left_join(., BLK.close, by='hour3') 	%>%     left_join(., PASC.close, by='hour3') 	%>%     left_join(., GAS.close, by='hour3') 	%>%     left_join(., GRC.close, by='hour3') 	%>%     left_join(., SBD.close, by='hour3') 	%>%     left_join(., XCP.close, by='hour3') 	%>%     left_join(., BTM.close, by='hour3') 	%>%     left_join(., EXP.close, by='hour3') 	%>%     left_join(., VIA.close, by='hour3') 	%>%     left_join(., BTCD.close, by='hour3') 	%>%     left_join(., RADS.close, by='hour3') 	%>%     left_join(., FLO.close, by='hour3') 	%>%     left_join(., NEOS.close, by='hour3') 	%>%     left_join(., NMC.close, by='hour3') 	%>%     left_join(., NXC.close, by='hour3') 	%>%     left_join(., XBC.close, by='hour3') 	%>%     left_join(., XVC.close, by='hour3') 	%>%     left_join(., PINK.close, by='hour3') 	%>%     left_join(., OMNI.close, by='hour3') 	%>%     left_join(., BELA.close, by='hour3') 	%>%     left_join(., BCY.close, by='hour3') 	%>%     left_join(., HUC.close, by='hour3') 	%>%     left_join(., XPM.close, by='hour3') 
#Conversion to USDT
coin<-c("BTC","LTC","ETH","XRP","BCH","STR","XMR","XEM","ETC","DASH","STRAT","NXT","ZEC","EMC2","ARDR","LSK","DOGE","VTC","BTS","OMG","SC","DGB","FCT","MAID","FLDC","VRC","REP","ZRX","GNO","CVC","DCR","GNT","SYS","STEEM","GAME","LBC","NAV","BCN","AMP","CLAM","POT","STORJ","RIC","BURST","PPC","BLK","PASC","GAS","GRC","SBD","XCP","BTM","EXP","VIA","BTCD","RADS","FLO","NEOS","NMC","NXC","XBC","XVC","PINK","OMNI","BELA","BCY","HUC","XPM")
colnames(full)<-c("Time",coin)

for(i in 2:length(coin)){
  full[,coin[i]]<-full[,"BTC"]*full[,coin[i]]
}

saveRDS(full, "Coins.RDS")
